add wave -position end  sim:/Lab5_VGAcontroller/clk_100Mhz
add wave -position end  sim:/Lab5_VGAcontroller/clk_25Mhz
add wave -position end  sim:/Lab5_VGAcontroller/hcount
add wave -position end  sim:/Lab5_VGAcontroller/vcount
add wave -position end  sim:/Lab5_VGAcontroller/Hsync
add wave -position end  sim:/Lab5_VGAcontroller/Vsync
add wave -position end  sim:/Lab5_VGAcontroller/displaySig
add wave -position end  sim:/Lab5_VGAcontroller/vgaRed
add wave -position end  sim:/Lab5_VGAcontroller/vgaGreen
add wave -position end  sim:/Lab5_VGAcontroller/vgaBlue