# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Jeremiah/Programming/ee460M/lab5_p1/lab5_p1.cache/wt [current_project]
set_property parent.project_path C:/Users/Jeremiah/Programming/ee460M/lab5_p1/lab5_p1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  C:/Users/Jeremiah/Programming/ee460M/DFF.v
  C:/Users/Jeremiah/Programming/ee460M/Lab4clock.v
  C:/Users/Jeremiah/Programming/ee460M/Lab5_VGAcontroller.v
  C:/Users/Jeremiah/Programming/ee460M/lab5_p1/lab5_p1.srcs/sources_1/new/Lab5_PartB.v
}
read_xdc C:/Users/Jeremiah/Programming/ee460M/Basys3_Master_lab5.xdc
set_property used_in_implementation false [get_files C:/Users/Jeremiah/Programming/ee460M/Basys3_Master_lab5.xdc]

synth_design -top Lab5_PartB -part xc7a35tcpg236-1
write_checkpoint -noxdef Lab5_PartB.dcp
catch { report_utilization -file Lab5_PartB_utilization_synth.rpt -pb Lab5_PartB_utilization_synth.pb }
