# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Jeremiah/Programming/ee460M/lab7A/lab7A.cache/wt [current_project]
set_property parent.project_path C:/Users/Jeremiah/Programming/ee460M/lab7A/lab7A.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  C:/Users/Jeremiah/Programming/ee460M/lab7/clockDivider.v
  C:/Users/Jeremiah/Programming/ee460M/lab7/lab7.v
}
read_xdc C:/Users/Jeremiah/Programming/ee460M/lab7/Basys3_Master_lab7a.xdc
set_property used_in_implementation false [get_files C:/Users/Jeremiah/Programming/ee460M/lab7/Basys3_Master_lab7a.xdc]

synth_design -top Complete_MIPS -part xc7a35tcpg236-1
write_checkpoint -noxdef Complete_MIPS.dcp
catch { report_utilization -file Complete_MIPS_utilization_synth.rpt -pb Complete_MIPS_utilization_synth.pb }
