# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {1}  -id {Synth 8-295}  -string {{WARNING: [Synth 8-295] found timing loop. [C:/Users/Jeremiah/Programming/ee460M/Lab4decrementer.v:17]}}  -suppress 
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Jeremiah/Programming/ee460M/lab4/lab4.cache/wt [current_project]
set_property parent.project_path C:/Users/Jeremiah/Programming/ee460M/lab4/lab4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  C:/Users/Jeremiah/Programming/ee460M/Lab4decrementer.v
  C:/Users/Jeremiah/Programming/ee460M/Lab4Debouncer.v
  C:/Users/Jeremiah/Programming/ee460M/Lab4BCDto7Segment.v
  C:/Users/Jeremiah/Programming/ee460M/Lab4BinaryToBCD.v
  C:/Users/Jeremiah/Programming/ee460M/Lab4clock.v
  C:/Users/Jeremiah/Programming/ee460M/Lab4Controller.v
  C:/Users/Jeremiah/Programming/ee460M/Lab4parkingMeterTop.v
}
read_xdc C:/Users/Jeremiah/Programming/ee460M/Basys3_Master_lab4.xdc
set_property used_in_implementation false [get_files C:/Users/Jeremiah/Programming/ee460M/Basys3_Master_lab4.xdc]

synth_design -top Lab4parkingMeterTop -part xc7a35tcpg236-1
write_checkpoint -noxdef Lab4parkingMeterTop.dcp
catch { report_utilization -file Lab4parkingMeterTop_utilization_synth.rpt -pb Lab4parkingMeterTop_utilization_synth.pb }
